CREATE TABLE transcript
( 	ID INT(11) NOT NULL AUTO_INCREMENT,
	STUDENT_NAME VARCHAR(200) NOT NULL,
	SCHOOL_NAME VARCHAR(400) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
	DEGREE_DATE DATE NOT NULL,
	DEGREE_DURATION INT(10),
	MAJOR VARCHAR(100),
	OVERALL_GPA VARCHAR(10),
	DEGREE_COMPLETION_TIME_YRS INT(2),
   CONSTRAINT TRANSCRIPT_PK PRIMARY KEY (ID)
);

CREATE TABLE GRADE_CONVERTOR
( 	ID INT(11) NOT NULL AUTO_INCREMENT,
    COUNTRY VARCHAR(200) NOT NULL,
    SCALE_MIN INT NOT NULL,
    SCALE_MAX INT NOT NULL,
	  DESCRIPTION VARCHAR(300) NOT NULL,
	  US_GRADE VARCHAR(10),
	  CONSTRAINT GRADE_CONVERTOR_PK PRIMARY KEY (ID)
);

CREATE TABLE SCHOOL
( 	ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    RANKING INT(10) NOT NULL,
	  RANKING_SOURCE VARCHAR(500) NOT NULL,
	  CONSTRAINT SCHOOL_PK PRIMARY KEY (ID)
);

CREATE TABLE USER
( 	ID INT(11) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(10) NOT NULL,
    PASSWORD INT(50) NOT NULL,
	SCHOOL VARCHAR(500) NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (ID)
);